### ISSUE TITLE
VPC execution role not attached

### ISSUE THREAD

**Issue by rstml** [cloudposse/terraform-aws-lambda-function#13]
I was trying to connect lambda to VPC and it failed with the following error:

"The provided execution role does not have permissions to call CreateNetworkInterface on EC2"

The config simply had these additional lines:

```
  vpc_config = {
    security_group_ids = ["sg-xxxxxxxxxx"]
    subnet_ids         = data.terraform_remote_state.parent.outputs.vpc_private_subnet_ids
  }
```

I believe there's a typo at the following line as it should be `var.vpc_config != null`:

https://github.com/cloudposse/terraform-aws-lambda-function/blob/cb734da0a221f49477b95cc80c598bb7e97f9a83/iam-role.tf#L35

I haven't tested it though.

Temporarily resolved by adding VPC permissions through custom lambda policy.

**Comment by jamengual** [comment]
https://github.com/cloudposse/terraform-aws-lambda-function/blob/main/iam-role.tf

line 34, you just need to enable that.

**Comment by manifestori** [comment]
On the first apply, it will fail to create the Lambda. It looks like a race condition between the creation of the lambda and the attachment of the role.
